name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Update dependencies
      run: composer update --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test-coverage

    - name: PHPUnit Tests
      uses: php-actions/phpunit@v3
      env:
        XDEBUG_MODE: coverage
      with:
        version: '11.3.1'
        php-version: '8.2.20'
        bootstrap: vendor/autoload.php
        configuration: phpunit.xml.dist
        php_extensions: xdebug
        args: tests --coverage-clover ./build/coverage.xml

    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODE_COV_TOKEN }}
        files: ./coverage.xml
        verbose: true
