name: Tagger

on:
    workflow_run:
        workflows: [ "Release" ]
        types:
            - completed
        branches:
            - master
        tags-ignore:
            - 'v*'

jobs:
    tagger:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@master
                with:
                    fetch-depth: 0

            -   name: Executar script de incremento de versão
                id: incrementar_versao
                run: ./incrementor.sh ${{ github.sha }}

            -   name: Update CHANGELOG
                id: changelog
                uses: requarks/changelog-action@v1
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    tag: ${{ env.version }}

            -   name: Create Release
                id: create_release
                uses: actions/create-release@latest
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ env.version }}
                    release_name: Release ${{ env.version }}
                    body: ${{ steps.changelog.outputs.changes }}
                    draft: false
                    prerelease: false
